import httpx
from typing import List

class PRPublisher:
    """Posts code review suggestions to GitHub PRs"""
    
    def __init__(self, github_token: str):
        self.github_token = github_token
        self.base_headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    async def publish_review_to_pr(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        suggestions: List[dict]
    ) -> dict:
        """
        Post AI review as a general PR comment (no line-level comments).

        Uses payload:
          { "body": "<markdown>", "event": "COMMENT" }

        Let httpx raise HTTPStatusError so callers can inspect GitHub's error body/status.
        """
        url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pull_number}/reviews"
        
        # Format suggestions into a single comprehensive markdown comment
        comment_body = "# 🤖 AI Code Review\n\n"
        if not suggestions:
            comment_body += "_No suggestions generated._\n\n"
        else:
            for suggestion in suggestions:
                fname = suggestion.get("file", "unknown")
                comment = suggestion.get("comment", "").strip()
                comment_body += f"## File: `{fname}`\n\n"
                comment_body += (comment or "_No comment provided._") + "\n\n"
        
        comment_body += "---\n*Generated by AI Code Review Assistant*"
        
        payload = {
            "body": comment_body,
            "event": "COMMENT"
        }
        
        # Let httpx raise HTTPStatusError on non-2xx so upstream can handle/report GitHub errors
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url,
                json=payload,
                headers=self.base_headers
            )
            response.raise_for_status()
            return response.json()
